[versions]
junit = "6.0.2"

[libraries]
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
hamcrest = { module = "org.hamcrest:hamcrest", version = "3.0" }
mps-launcher = { module = "de.itemis.mps.build-backends:launcher", version = "2.8.0.167.c51149b" }
